#!/bin/bash

# Простой mock для OrcaSlicer для тестирования
# Создает mock G-code файл вместо настоящего слайсинга

OUTPUT_FILE=""
INPUT_FILE=""

# Парсим аргументы
while [[ $# -gt 0 ]]; do
    case $1 in
        --output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --export-gcode)
            shift
            ;;
        *.stl)
            INPUT_FILE="$1"
            shift
            ;;
        *)
            shift
            ;;
    esac
done

# Создаем mock G-code файл
if [[ -n "$OUTPUT_FILE" && -n "$INPUT_FILE" ]]; then
    cat > "$OUTPUT_FILE" << 'EOF'
; Generated by OrcaSlicer Mock
; filament used [mm] = 125.5
; filament used [g] = 0.29
; estimated printing time = 0h 12m 45s
; layer count: 40
; layer height: 0.25
; filament_type = PLA

G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
G28 ; home all axes

; Start printing
G1 Z0.25 F1200.0
G1 X10 Y10 F1500.0
G1 E1.0 F900.0

; Layer 1
G1 X20 Y10 E1.5
G1 X20 Y20 E2.0
G1 X10 Y20 E2.5
G1 X10 Y10 E3.0

; End of print
M104 S0 ; turn off extruder  
M140 S0 ; turn off bed
G28 X0  ; home X axis
M84 ; disable motors
EOF
    echo "Mock slicing completed: $INPUT_FILE -> $OUTPUT_FILE"
    exit 0
else
    echo "Error: Missing output file or input file"
    exit 1
fi