; Generated by OrcaSlicer Test Mock
; filament used [mm] = 150.5
; filament used [g] = 0.35
; estimated printing time = 0h 15m 30s
; layer count: 50
; layer height: 0.2
; filament_type = PLA

G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
G28 ; home all axes

; Start printing
G1 Z0.2 F1200.0
G1 X10 Y10 F1500.0
G1 E1.0 F900.0

; Layer 1
G1 X20 Y10 E1.5
G1 X20 Y20 E2.0
G1 X10 Y20 E2.5
G1 X10 Y10 E3.0

; End of print
M104 S0 ; turn off extruder
M140 S0 ; turn off bed
G28 X0  ; home X axis
M84 ; disable motors